{
   "kind" : "pipeline",
   "name" : "default",
   "steps" : [
      {
         "commands" : [
            "cd \u005C/app",
            "perl local/bin/pmbp.pl --install-commands docker",
            "cd /drone/src",
            "pwd",
            "pwd",
            "make test-deps",
            "make test",
            "ls",
            "docker version"
         ],
         "image" : "quay.io/wakaba/docker-perl-app-base",
         "name" : "build",
         "volumes" : [
            {
               "name" : "dockersock",
               "path" : "/var/run/docker.sock"
            }
         ]
      }
   ],
   "type" : "docker",
   "volumes" : [
      {
         "host" : {
            "path" : "/var/run/docker.sock"
         },
         "name" : "dockersock"
      }
   ]
}
