{
   "kind" : "pipeline",
   "name" : "default",
   "steps" : [
      {
         "commands" : [
            "perl -e 'print \u0022/var/lib/docker/shareddir/\u0022 . rand' > .ciconfigdockershareddir",
            "mkdir -p `cat .ciconfigdockershareddir`",
            "bash -c cd\u005C \u005C\u005C\u005C/app\u005C \u005C&\u005C&\u005C perl\u005C local\u005C/bin\u005C/pmbp\u005C.pl\u005C \u005C-\u005C-install\u005C-commands\u005C docker",
            "perl -e 'print \u0022ciconfig-\u0022 . rand' > .ciconfigdockername",
            "docker run --name `cat .ciconfigdockername` -v `cat .ciconfigdockershareddir`:`cat .ciconfigdockershareddir` -v /var/run/docker.sock:/var/run/docker.sock -d -t quay.io/wakaba/docker-perl-app-base bash",
            "pwd",
            "cat .ciconfigdockershareddir",
            "ls `cat .ciconfigdockershareddir`",
            "pwd",
            "echo foo > bar",
            "make test-deps",
            "make test",
            "cat bar",
            "ls",
            "docker version"
         ],
         "image" : "quay.io/wakaba/docker-perl-app-base",
         "name" : "build",
         "volumes" : [
            {
               "name" : "dockersock",
               "path" : "/var/run/docker.sock"
            },
            {
               "name" : "dockershareddir",
               "path" : "/var/lib/docker/shareddir"
            }
         ]
      },
      {
         "commands" : [
            "docker stop `cat .ciconfigdockername`",
            "docker logs --tail 50 `cat .ciconfigdockername`",
            "rm -fr `cat .ciconfigdockershareddir`"
         ],
         "image" : "quay.io/wakaba/docker-perl-app-base",
         "name" : "cleanup-nested",
         "when" : {
            "status" : [
               "failure",
               "success"
            ]
         }
      }
   ],
   "type" : "docker",
   "volumes" : [
      {
         "host" : {
            "path" : "/var/run/docker.sock"
         },
         "name" : "dockersock"
      },
      {
         "host" : {
            "path" : "/var/lib/docker/shareddir"
         },
         "name" : "dockershareddir"
      }
   ]
}
