{
   "kind" : "pipeline",
   "name" : "default",
   "steps" : [
      {
         "commands" : [
           "bash -c 'while [ true ]; do perl -e warn; sleep 1; done' &",
           "sleep 30",
           "echo done"
         ],
         "image" : "quay.io/wakaba/droneci-step-base",
         "name" : "build",
         "volumes" : [
            {
               "name" : "dockersock",
               "path" : "/var/run/docker.sock"
            },
            {
               "name" : "dockershareddir",
               "path" : "/var/lib/docker/shareddir"
            }
         ]
      },
      {
         "commands" : [
            "bash -c cd\u005C \u005C\u005C\u005C/app\u005C \u005C&\u005C&\u005C perl\u005C local\u005C/bin\u005C/pmbp\u005C.pl\u005C \u005C-\u005C-install\u005C-commands\u005C docker",
            "cat bar",
            "ls"
         ],
         "depends_on" : [
            "build"
         ],
         "environment" : {
            "CIRCLE_NODE_INDEX" : "0",
            "CIRCLE_NODE_TOTAL" : "1"
         },
         "image" : "quay.io/wakaba/droneci-step-base",
         "name" : "test--test1",
         "volumes" : [
            {
               "name" : "dockersock",
               "path" : "/var/run/docker.sock"
            },
            {
               "name" : "dockershareddir",
               "path" : "/var/lib/docker/shareddir"
            }
         ]
      },
      {
         "commands" : [
            "bash -c cd\u005C \u005C\u005C\u005C/app\u005C \u005C&\u005C&\u005C perl\u005C local\u005C/bin\u005C/pmbp\u005C.pl\u005C \u005C-\u005C-install\u005C-commands\u005C docker",
            "docker version"
         ],
         "depends_on" : [
            "build"
         ],
         "environment" : {
            "CIRCLE_NODE_INDEX" : "0",
            "CIRCLE_NODE_TOTAL" : "1"
         },
         "image" : "quay.io/wakaba/droneci-step-base",
         "name" : "test--test2",
         "volumes" : [
            {
               "name" : "dockersock",
               "path" : "/var/run/docker.sock"
            },
            {
               "name" : "dockershareddir",
               "path" : "/var/lib/docker/shareddir"
            }
         ]
      },
      {
         "commands" : [
            "bash -c cd\u005C \u005C\u005C\u005C/app\u005C \u005C&\u005C&\u005C perl\u005C local\u005C/bin\u005C/pmbp\u005C.pl\u005C \u005C-\u005C-install\u005C-commands\u005C docker",
            "make test"
         ],
         "depends_on" : [
            "build"
         ],
         "environment" : {
            "CIRCLE_NODE_INDEX" : "0",
            "CIRCLE_NODE_TOTAL" : "1"
         },
         "image" : "quay.io/wakaba/droneci-step-base",
         "name" : "test-pmbp",
         "volumes" : [
            {
               "name" : "dockersock",
               "path" : "/var/run/docker.sock"
            },
            {
               "name" : "dockershareddir",
               "path" : "/var/lib/docker/shareddir"
            }
         ]
      },
      {
         "commands" : [
            "bash -c cd\u005C \u005C\u005C\u005C/app\u005C \u005C&\u005C&\u005C perl\u005C local\u005C/bin\u005C/pmbp\u005C.pl\u005C \u005C-\u005C-install\u005C-commands\u005C docker",
            "docker stop `cat /drone/src/local/ciconfig/dockername`",
            "rm -fr `cat /drone/src/local/ciconfig/dockershareddir`"
         ],
         "depends_on" : [
            "build",
            "test--test1",
            "test--test2",
            "test-pmbp"
         ],
         "failure" : "ignore",
         "image" : "quay.io/wakaba/droneci-step-base",
         "name" : "cleanup-nested",
         "volumes" : [
            {
               "name" : "dockersock",
               "path" : "/var/run/docker.sock"
            },
            {
               "name" : "dockershareddir",
               "path" : "/var/lib/docker/shareddir"
            }
         ],
         "when" : {
            "status" : [
               "failure",
               "success"
            ]
         }
      }
   ],
   "type" : "docker",
   "volumes" : [
      {
         "host" : {
            "path" : "/var/run/docker.sock"
         },
         "name" : "dockersock"
      },
      {
         "host" : {
            "path" : "/var/lib/docker/shareddir"
         },
         "name" : "dockershareddir"
      }
   ],
   "workspace" : {
      "path" : "/drone/src"
   }
}
