{
   "kind" : "pipeline",
   "name" : "default",
   "steps" : [
      {
         "commands" : [
         ],
         "image" : "quay.io/wakaba/docker-perl-app-base",
         "name" : "build"
      }
   ],
   "type" : "docker"
}
