{
   "kind" : "pipeline",
   "name" : "default",
   "steps" : [
      {
         "commands" : [
            "make test-deps",
            "make test",
            "ls",
            "docker version"
         ],
         "image" : "quay.io/wakaba/docker-perl-app-base",
         "name" : "build"
      }
   ],
   "type" : "docker"
}
