{
   "kind" : "pipeline",
   "name" : "default",
   "steps" : [
      {
         "commands" : [
            "perl -e 'print \u0022/var/lib/docker/shareddir/\u0022 . rand' > .ciconfigdockershareddir",
            "mkdir -p `cat .ciconfigdockershareddir`",
            "bash -c cd\u005C \u005C\u005C\u005C/app\u005C \u005C&\u005C&\u005C perl\u005C local\u005C/bin\u005C/pmbp\u005C.pl\u005C \u005C-\u005C-install\u005C-commands\u005C docker",
            "perl -e 'print \u0022ciconfig-\u0022 . rand' > .ciconfigdockername",
            "docker run --name `cat .ciconfigdockername` -v `cat .ciconfigdockershareddir`:`cat .ciconfigdockershareddir` -v /var/run/docker.sock:/var/run/docker.sock -d -t quay.io/wakaba/docker-perl-app-base bash",
            "pwd",
            "cat .ciconfigdockershareddir",
            "ls `cat .ciconfigdockershareddir`",
            "cp -R . `cat .ciconfigdockershareddir`/app",
            "docker exec -t `cat .ciconfigdockername` bash -c cd\u005C `cat .ciconfigdockershareddir`\u005C \u005C&\u005C&\u005C cd\u005C app\u005C \u005C&\u005C&\u005C ls\u005C \u005C&\u005C&\u005C pwd",
            "docker exec -t `cat .ciconfigdockername` -e CI='$CI' -e DRONE_COMMIT_SHA='$DRONE_COMMIT_SHA' bash -c echo\u005C \u005C$DRONE_COMMIT_SHA",
            "docker exec -t `cat .ciconfigdockername` -e CI='$CI' -e DRONE_COMMIT_SHA='$DRONE_COMMIT_SHA' bash -c cd\u005C `cat .ciconfigdockershareddir`\u005C \u005C&\u005C&\u005C cd\u005C app\u005C \u005C&\u005C&\u005C make\u005C pmbp\u005C-install",
            "docker exec -t `cat .ciconfigdockername` bash -c cd\u005C `cat .ciconfigdockershareddir`\u005C \u005C&\u005C&\u005C cd\u005C app\u005C \u005C&\u005C&\u005C \u005C.\u005C/perl\u005C local\u005C/bin\u005C/pmbp\u005C.pl\u005C \u005C-\u005C-install\u005C-module\u005C IO\u005C:\u005C:Interface\u005C:\u005C:Simple",
            "docker exec -t `cat .ciconfigdockername` bash -c cd\u005C `cat .ciconfigdockershareddir`\u005C \u005C&\u005C&\u005C cd\u005C app\u005C \u005C&\u005C&\u005C \u005C.\u005C/perl\u005C \u005C-MIO\u005C:\u005C:Interface\u005C:\u005C:Simple\u005C \u005C-e\u005C \u005C'print\u005C IO\u005C:\u005C:Interface\u005C:\u005C:Simple\u005C-\u005C>new\u005C \u005C(q\u005C{eth0\u005C}\u005C)\u005C-\u005C>address\u005C'\u005C \u005C>\u005C ipaddr",
            "docker exec -t `cat .ciconfigdockername` bash -c cd\u005C `cat .ciconfigdockershareddir`\u005C \u005C&\u005C&\u005C cd\u005C app\u005C \u005C&\u005C&\u005C cat\u005C ipaddr",
            "echo foo > bar",
            "make test-deps",
            "make test",
            "cat bar",
            "ls",
            "docker version"
         ],
         "image" : "quay.io/wakaba/docker-perl-app-base",
         "name" : "build",
         "volumes" : [
            {
               "name" : "dockersock",
               "path" : "/var/run/docker.sock"
            },
            {
               "name" : "dockershareddir",
               "path" : "/var/lib/docker/shareddir"
            }
         ]
      },
      {
         "commands" : [
            "bash -c cd\u005C \u005C\u005C\u005C/app\u005C \u005C&\u005C&\u005C perl\u005C local\u005C/bin\u005C/pmbp\u005C.pl\u005C \u005C-\u005C-install\u005C-commands\u005C docker",
            "docker stop `cat .ciconfigdockername`",
            "rm -fr `cat .ciconfigdockershareddir`"
         ],
         "image" : "quay.io/wakaba/docker-perl-app-base",
         "name" : "cleanup-nested",
         "volumes" : [
            {
               "name" : "dockersock",
               "path" : "/var/run/docker.sock"
            },
            {
               "name" : "dockershareddir",
               "path" : "/var/lib/docker/shareddir"
            }
         ],
         "when" : {
            "status" : [
               "failure",
               "success"
            ]
         }
      }
   ],
   "type" : "docker",
   "volumes" : [
      {
         "host" : {
            "path" : "/var/run/docker.sock"
         },
         "name" : "dockersock"
      },
      {
         "host" : {
            "path" : "/var/lib/docker/shareddir"
         },
         "name" : "dockershareddir"
      }
   ]
}
