
kind: pipeline
type: docker
name: default

steps:
- name: buikd
  image: debian
  commands:
  - ls
  - df
  - uname --all
  - apt-get update && apt-get install -y docker-io
  - docker pull debian
  - docker pull quay.io/wakaba/firefoxdriver:stable
