install:
  - git clone https://github.com/dnmfarrell/berrybrew
  - berrybrew\bin\berrybrew available
  - berrybrew\bin\berrybrew install 5.20.3_64
  - where perl
  #- mkdir bin
  - curl -f -L "https://github.com/mohawk2/dmake/archive/DMAKE_4_12_2_2.zip" > DMAKE.zip
  - unzip DMAKE.zip
  #- curl -f -L "http://downloads.sourceforge.net/project/mingw/Installer/mingw-get/mingw-get-0.6.2-beta-20131004-1/mingw-get-0.6.2-mingw32-beta-20131004-1-bin.zip" > get.zip
  #- unzip get.zip
  - set PATH=%CD%\dmake-DMAKE_4_12_2_2;%PATH%
  #- echo %PATH%
  #- bin\mingw-get install mingw32-make gcc
  #- copy bin\mingw32-make.exe bin\make.exe
  #- make
  #- ps: Start-FileDownload "http://strawberryperl.com/download/5.8.8/strawberry-perl-5.8.8.1-1.zip" -FileName "perl.zip"
  #- curl -f -L "http://kent.dl.sourceforge.net/project/unigw/unzip/5.50/unzip.exe" > unzip.exe
  #- .\unzip.exe perl.zip > NUL
  - curl -f -L https://raw.githubusercontent.com/wakaba/perl-setupenv/staging/bin/pmbp.pl > pmbp.pl
build_script:
  #- perl\bin\perl.exe pmbp.pl --install-module Path::Tiny
  - where perl
  - perl pmbp.pl --install-module Path::Tiny
  - perl pmbp.pl --install-module Encode
  - perl pmbp.pl --install-perl
  - curl http://wiki.suikawiki.org > wiki.html
  - type wiki.html
test_script:
  - ps: Start-FileDownload 'http://suikawiki.org' -FileName "sw.html"
  - dir
