FROM quay.io/wakaba/base:sid

ADD mirrordata/ /app/data/mirror/@@MIRROR_SET@@/


## =head1 LICENSE
## 
## Copyright 2024 Wakaba <wakaba@suikawiki.org>.
## 
## This library is free software; you can redistribute it and/or modify
## it under the same terms as Perl itself.
## 
## =cut
