{
   "jobs" : {
      "build" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/build"
         },
         "machine" : {
            "image" : "default"
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "make ddsd-batch"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/build"
               }
            },
            {
               "persist_to_workspace" : {
                  "paths" : [
                     ".ciconfigtemp"
                  ],
                  "root" : "./"
               }
            }
         ]
      },
      "deploy_master" : {
         "machine" : {
            "image" : "default"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "deploy" : {
                  "command" : "make deploy-master"
               }
            }
         ]
      },
      "test" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/test"
         },
         "machine" : {
            "image" : "default"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "true"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/test"
               }
            }
         ]
      }
   },
   "version" : "2.1",
   "workflows" : {
      "autobuild" : {
         "jobs" : [
            "build",
            {
               "test" : {
                  "requires" : [
                     "build"
                  ]
               }
            },
            {
               "deploy_master" : {
                  "context" : [
                     "deploy-context"
                  ],
                  "requires" : [
                     "build",
                     "test"
                  ]
               }
            }
         ],
         "triggers" : [
            {
               "schedule" : {
                  "cron" : "29 11 * * *",
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "master"
                        ]
                     }
                  }
               }
            }
         ]
      },
      "build" : {
         "jobs" : [
            {
               "build" : {
               }
            },
            {
               "test" : {
                  "requires" : [
                     "build"
                  ]
               }
            },
            {
               "deploy_master" : {
                  "context" : [
                     "deploy-context"
                  ],
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "master"
                        ]
                     }
                  },
                  "requires" : [
                     "build",
                     "test"
                  ]
               }
            }
         ]
      },
      "version" : 2
   }
}
