{
   "jobs" : {
     "build1": {
       "machine" : {
                 "enabled" : true
       },
       "steps": [
         {"run": {"command": "echo 1"}}
       ]
     },
     "build2": {
       "machine" : {
                 "enabled" : true
       },
       "steps": [
         {"run": {"command": "echo 2"}}
       ]
     }
   },
   "version" : 2,
   "workflows" : {
      "version" : 2,
      "build": {
        "jobs": ["build1", "build2"]
      }
   }
}
