{
   "jobs" : {
     "build1": {
       "machine" : {
                 "enabled" : true
       },
       "steps": [
         "checkout",
         {"run": {"command": "echo 1; mkdir -p /tmp/abc/foo; echo 1 > /tmp/abc/foo/aaa.txt"}},
         {"run": {"command": "docker build -t dockertest1 docker"}},
         {"run": {"command": "docker save -o /tmp/abc/foo/dockertest1.tar dockertest1"}},
         {"persist_to_workspace": {
           "root": "/tmp/abc",
           "paths": ["foo"]
         }}

]
     },
     "build2": {
       "machine" : {
                 "enabled" : true
       },
       "steps": [
         {"attach_workspace": {"at": "/tmp/abc"}},
         {"run": {"command": "docker load -i /tmp/abc/foo/dockertest1.tar"}},
         {"run": {"command": "echo 2; cat /tmp/abc/foo/aaa.txt"}},
         {"run": {"command": "docker run -it dockertest1"}}
       ]
     }
   },
   "version" : 2,
   "workflows" : {
      "version" : 2,
      "build": {
        "jobs": [
          "build1",
          {"build2": {"requires": ["build1"], "filters": {"branches": {"only": "staging"}}}},
          {"build3": {"requires": ["build1"], "filters": {"branches": {"only": "build3branch"}}}}

        ]
      }
   }
}
