{
   "jobs" : {
     "build1": {
       "machine" : {
                 "enabled" : true
       },
       "steps": [
         {"run": {"command": "echo 1; mkdir -p /tmp/abc/foo; echo 1 > /tmp/abc/foo/aaa.txt"}},
         {"persist_to_workspace": {
           "root": "/tmp/abc",
           "paths": ["foo"]
         }}
       ]
     },
     "build2": {
       "machine" : {
                 "enabled" : true
       },
       "steps": [
         {"attach_workspace": {"at": "/tmp/abc"}},
         {"run": {"command": "echo 2; cat /tmp/abc/foo/aaa.txt"}}
       ]
     }
   },
   "version" : 2,
   "workflows" : {
      "version" : 2,
      "build": {
        "jobs": ["build1", {"build2": {"requires": ["build1"]}}]
      }
   }
}
