{
  "name": "abc",
  "on": {
    "push": {},
    "schedule": [{"cron": "25 6 5 10 *"}]
  },
  "jobs": {
    "foo": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {"uses": "actions/checkout@v2"},
        {"run": "ls /"},
        {"run": "pwd; ls"},
        {"run": "echo $EN1"},
        {"run": "echo $EN2"},
        {"run": "echo $X1",
         "env": {"X1": "${{ secrets.EN1 }}"}},
        {"run": "echo $X2",
         "env": {"X2": "${{ secrets.EN2 }}"}}
      ]
    },
    "bar": {
      "runs-on": "macos-latest",
      "needs": ["foo"],
      "steps": [
        {"uses": "actions/checkout@v2"},
        {"run": "echo $ABC_D",
         "env": {"ABC_D": "12"}},
        {"run": "mkdir abc; echo AAA > abc/d"},
        {"run": "mkdir abc/dd; echo AAA2 > abc/dd/e"},
        {"uses": "actions/upload-artifact@v2",
         "with": {"name": "artifact-abc", "path": "abc"}}
      ]
    },
    "baz": {
      "strategy": {
        "matrix": {
          "os": ["ubuntu-latest", "windows-latest"]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "needs": ["foo", "bar"],
      "steps": [
        {"uses": "actions/checkout@v2"},
        {"uses": "actions/download-artifact@v2",
         "with": {"name": "artifact-abc"}},
        {"run": "echo $ABC_D",
         "env": {"ABC_D": "12"}},
        {"run": "ls -R ."},
        {"run": "cat d"},
        {"run": "cat dd/e"},
        {"run": "ls"}
      ]
    }
  }
}