{
  "name": "cron",
  "on": {
    "schedule": [{"cron": "*/5 2 * * *"}]
  },
  "jobs": {
    "foo": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {"run": "date"},
        {"run": "ls /"}
      ]
    }
  }
} 
 
 
